Initial Implementation of Nexus Class
NOAA-OWP/hypy pull request #8
Opened 2020-09-17 15:18 UTC by jdmattern-noaa

Python implementation of HY Features Nexus class with pytest unit tests.

(See Github Issue: #3 )

## Testing

1. pytest unit tests added

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

2020-09-18 14:19 UTC, robertbartel requested changes
I think a few things need to be changed (using [this diagram](https://docs.opengeospatial.org/is/14-111r6/14-111r6.html#_hydro_feature_concepts) reference, so if you have something more recent you are going by, that may invalidate some or all of my suggestions):

- `to_id` needs to be renamed to something like `receiving_catchments` and made into a list of _Catchment_ objects
- an analogous `contributing_catchments` property needs to be created, supported in `__init__`, etc.
- a `realization` property is also needed to reference the Nexus's realization, although I don't think we have a type (i.e., _HydroLocation_) to reference for that just yet

2020-09-18 20:26 UTC, jdmattern-noaa commented
> I think a few things need to be changed (using [this diagram](https://docs.opengeospatial.org/is/14-111r6/14-111r6.html#_hydro_feature_concepts) reference, so if you have something more recent you are going by, that may invalidate some or all of my suggestions):
> 
> * `to_id` needs to be renamed to something like `receiving_catchments` and made into a list of _Catchment_ objects
> * an analogous `contributing_catchments` property needs to be created, supported in `__init__`, etc.
> * a `realization` property is also needed to reference the Nexus's realization, although I don't think we have a type (i.e., _HydroLocation_) to reference for that just yet

Above have been fixed.

2020-09-22 12:46 UTC, hellkite500 approved these changes

2020-09-22 15:05 UTC, robertbartel approved these changes

2020-09-22 15:06 UTC, merged